config:
  spec:
    destination:
      server: https://kubernetes.default.svc
    source:
      repoURL: https://github.com/vadivkanag/argo-apps/edit/main/apps/values.yaml
      targetRevision: main

applications:
  - name: helm-blue-green-custdatasvc
    tool:
      helm:
        releaseName: helm-blue-green-custdatasvc
  - name: helm-custdatasvc
    tool:
      helm:
        releaseName: helm-custdatasvc
